### PR TITLE
New query order

### PR DESCRIPTION
**Pull request by qbereau**
Hi @rupurt!
First of all, thanks for your work on this library.

I wanted to add a way to be able to query an order (through its order_id or client_order_id) and while working on this, i realised that there seems to be a mismatch between the latest refactor of the new create_order/2 and the VCR that were used. I was always getting a `1104 UNREAD_PARAMETERS` error from binance when i deleted the VCR cassettes and it seems to be related because of some params that were sent being nil and that the change of attribute name (`recv_window` vs `recvWindow`) would actually send the wrongly-formatted name.
So my solution was to basically drop all nil attribute and use the proper param when non-nil (on http_client)

There was also some strange code errors being mapped to the actual wrong context (`2010` was set to insufficient funds while it's actually a NEW_ORDER_REJECTED error).

I also made some VCR tests slightly more resilient to use-cases (ie. depending on having a `FILLED` or `NEW` order) and i used the opportunity to basically test everything on Binance testnet.

Anyway, i wasn't expecting to have so many changes when starting on this. I did a similar thing on 0.0.5 (accessible here: https://github.com/qbereau/ex_binance/tree/query_order) that I unfortunately didn't PR at the time (that was before the `create_order` refacto and i didn't stumble upon all these issues).

Feel free to ask if you feel something's wrong here or you have some comments/questions.

### CODE REVIEW

**Comment by rupurt** [comment]
Thanks for this @qbereau LGTM

**Review by rupurt — APPROVED** [review]

**Comment by rupurt** [comment]
@qbereau can you rebase this with `main`? I made some changes to the config which should help with these CI failures

**Comment by rupurt** [comment]
@qbereau sorry. 1 more rebase...

**Comment by qbereau** [comment]
Done, let me know how it goes this time
Thanks!

**Comment by rupurt** [comment]
@qbereau ok. 1 last time, I promise lol...

External contributors can't access the secrets in PR's so I just hard coded them in the GHA. They're just mock secrets in CI so not a security issue.

I also had to bump the min requirement for Elixir to v1.11. <= 1.10 doesn't support runtime env vars for application config.

**Comment by qbereau** [comment]
No worries! Just rebased

**Comment by rupurt** [comment]
Looks like you've got 1 genuine test failure. I'm also getting it locally

**Comment by qbereau** [comment]
My bad, didn't realise that one was failing.
Should be better now.

**Pull request merged**
